# Generated by Django 3.2.4 on 2021-07-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='Area',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='City',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='Division',
            field=models.CharField(blank=True, choices=[('Barishal', 'Barishal'), ('Chittagong', 'Chittagong'), ('Dhaka', 'Dhaka'), ('Mymensingh ', 'Mymensingh'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet')], max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='Last_date_of_donation',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, choices=[('Bangladesh', 'Bangladesh')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='donation_activity',
            field=models.CharField(choices=[('Available', 'Available'), ('No available', 'No available')], max_length=50),
        ),
    ]
