# Generated by Django 3.2.4 on 2021-08-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210716_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Last_date_of_donation',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='donation_activity',
            field=models.CharField(choices=[('Available', 'Available'), ('Unavailable', 'Unavailable')], max_length=50),
        ),
    ]
