# Generated by Django 3.2.4 on 2021-08-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210807_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, choices=[('Famale', 'Famale'), ('Male', 'Male'), ('3rd gender', '3rd gender')], max_length=200),
        ),
    ]
