# Generated by Django 3.2.4 on 2021-08-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210807_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Division',
            field=models.CharField(blank=True, choices=[('Barishal', 'Barishal'), ('Chittagong', 'Chittagong'), ('Dhaka', 'Dhaka'), ('Mymensingh ', 'Mymensingh'), ('Khulna', 'Khulna'), ('Rajshahi', 'Rajshahi'), ('Rangpur', 'Rangpur'), ('Sylhet', 'Sylhet')], max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='area',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='donation_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='donation_time',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hospital_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='patient_types',
            field=models.TextField(blank=True, null=True),
        ),
    ]
