# Generated by Django 3.2.4 on 2021-08-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210808_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(blank=True, choices=[('Famale', 'Famale'), ('Male', 'Male'), ('3rd gender', '3rd gender')], max_length=200),
        ),
    ]
